apiVersion: rmk.markruler.com/v1alpha1
kind: Machine
metadata:
  labels:
    app.kubernetes.io/name: k8s
    app.kubernetes.io/managed-by: kustomize
  name: machine-sample
spec:
  # role: worker
  role: garbage
